title: Calcigral
description: >- # this means to ignore newlines until "baseurl:"
  Calcigral is a simple command-line utility for approximating the value of definite integrals with one variable over a real line.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://calcigral.wlko.me" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  waleko

# Build settings
theme: minima
markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax
